# Environment-based configuration
# For local development: HUGO_ENV=development
# For production: HUGO_ENV=production
baseurl = "https://tomasjgonzalez-site.netlify.app/"
theme = "hc-starter"
languageCode = "en-gb"
title = "Tomás González"
pluralizelisttitles = false
# Enable for syntax highlighting
pygmentsUseClasses = true
# Enable highlighting for code fences
pygmentsCodeFences = true
# Get LastMod data from Git
enableGitInfo = true

# Enable Emojis
enableEmoji = true

[params]
keywords = "Product Design, UX Design, UI Design, Small businesses, Automation, Typography"
description = "Tomás González is an Experience designer based in Auckland, New Zealand."
strapline = "Experience designer"
location = "Auckland, New Zealand"
card_image = "img/card-image.png"
# Set Cloudinary URL for image hosting
cloudinary_url = "https://res.cloudinary.com/tomasgo/image/upload"

[params.author]
name = "Tomás González"
photo = "https://res.cloudinary.com/tomasgo/image/upload/v1739249919/tomas-master/img/Tomas-Gonzalez_j5g2cy.jpg"

[taxonomies]
topic = "topics"

[outputs]
home = ["HTML", "RSS"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[permalinks]
writing = "/:section/:slug/"
projects = "/:section/:slug/"
updates = "/:section/:slug/"
page = "/:slug/"

[markup]
[markup.goldmark]
duplicateResourceFiles = false
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
linkifyProtocol = 'https'
strikethrough = true
table = true
taskList = true
[markup.goldmark.extensions.extras]
[markup.goldmark.extensions.extras.insert]
enable = false
[markup.goldmark.extensions.extras.mark]
enable = true
[markup.goldmark.extensions.extras.subscript]
enable = false
[markup.goldmark.extensions.extras.superscript]
enable = false
[markup.goldmark.extensions.passthrough]
enable = false
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false # remove paragraphs that wrap stand-alone images

[[menu.main]]
name = "Index"
url = "/"
weight = 5

[[menu.main]]
name = "Accessibility"
url = "/accessibility/"
weight = 8

[[menu.main]]
name = "Writing"
url = "/writing/"
weight = 10

[[menu.main]]
name = "Inspirations"
url = "/inspirations/"
weight = 12

[[menu.main]]
name = "Portfolio"
url = "/portfolio/"
weight = 15

[[menu.footer]]
name = "Index"
url = "/"
weight = 5

[[menu.footer]]
name = "Accessibility"
url = "/accessibility/"
weight = 8

[[menu.footer]]
name = "Writing"
url = "/writing/"
weight = 10

[[menu.footer]]
name = "Inspirations"
url = "/inspirations/"
weight = 12

[[menu.footer]]
name = "Portfolio"
url = "/portfolio/"
weight = 15

[[menu.footer]]
name = "Topics"
url = "/topics/"
weight = 20

[[menu.footer]]
name = "Slashes"
url = "/slashes/"
weight = 25

