[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENV = "production"

[[redirects]]
  from = "/*"
  to = "https://www.harrycresswell.com/"
  status = 302