baseurl = "https://harrycresswell.com/"
languageCode = "en-us"
languageLang = "en"
title = "Harry Cresswell"
pluralizelisttitles = false
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

# Enable Disqus by removing comments
#disqusShortname = "harrycresswell"

# Enable Emojis because why the hell not
enableEmoji = true

# Enable for syntax highlighting
#pygmentsUseClasses=true
#PygmentsCodeFences = true
#pygmentsCodefencesGuessSyntax = true

[permalinks]
  articles = "/:section/:slug/"
  notes = "/:section/:slug/"
  page = "/:title/"
  custom = "/:slug/"

[params]
  keywords = "Product Design, UX Design, UI Design, Front-end Development, Small businesses, Automation, Typography"
  description = "Technical related blog posts on design and code by github.com/harrycresswell"
  strapline = "Product Design, User Experience Design, User Interface Design and Front-end Development"
  location = "London, UK"
  twitter = "@harrycresswell"
  # Set Cloudinary URL for image hosting
  cloudinary_url = "https://res.cloudinary.com/harrycresswell/image/upload"
  author = "Harry Cresswell"

[author]
  name = "Harry Cresswell"
  email = "studio@harrycresswell.com"

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Articles"
  url = "/articles/"
  weight = 5

[[menu.main]]
  name = "Newsletter"
  url = "/newsletter/"
  weight = 10

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 15

[[menu.footer]]
  name = "Imprint"
  url = "/imprint/"
  weight = 5

[[menu.footer]]
  name = "Mood"
  url = "https://mood.harrycresswell.com/"
  weight = 10

[[menu.footer]]
  name = "Notes"
  url = "/notes/"
  weight = 15

[[menu.mobile]]
  name = "Articles"
  url = "/articles/"
  weight = 5

[[menu.mobile]]
  name = "Newsletter"
  url = "/newsletter/"
  weight = 10

[[menu.mobile]]
  name = "Notes"
  url = "/notes/"
  weight = 15

[[menu.mobile]]
  name = "About"
  url = "/about/"
  weight = 20

[[menu.mobile]]
  name = "Imprint"
  url = "/imprint/"
  weight = 25

[[menu.mobile]]
  name = "Mood"
  url = "https://mood.harrycresswell.com/"
  weight = 30

