baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Harry Cresswell"
pluralizelisttitles = false

# Enable Disqus by removing comments
#disqusShortname = "harrycresswell"

# Enable Emojis because why the hell not
enableEmoji = true

[permalinks]
  articles = "/:section/:slug/"
  notes = "/:section/:slug/"
  page = "/:title/"

[params]
  keywords = "UX Design, UI Design, Front-end Development, Small businesses, Automation, Typography"
  description = "Technical related blog posts on design and code by github.com/harrycresswell"
  strapline = "User Interface Design and Development"
  location = "London, UK"
  twitter = "@harrycresswell"
  # Set Cloudinary URL for image hosting
  cloudinary_url = "https://res.cloudinary.com/harrycresswell/image/upload"
  author = "Harry Cresswell"

[author]
  name = "Harry Cresswell"
  email = "studio@harrycresswell.com"

[taxonomies]
  tag = "tags"

[[menu.main]]
  name = "Articles"
  url = "/articles/"
  weight = 5

[[menu.main]]
  name = "Newsletter"
  url = "/newsletter/"
  weight = 10

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 15

[[menu.footer]]
  name = "Imprint"
  url = "/imprint/"
  weight = 5

[[menu.footer]]
  name = "Mood"
  url = "https://thevastnothingnessofspace.tumblr.com/"
  weight = 10

[[menu.footer]]
  name = "Notes"
  url = "/notes/"
  weight = 15
