name = "HC Starter"
license = "MIT"
licenselink = "Link to theme's license"
description = "Theme description"
homepage = "Website of your theme"
tags = ["blog", "company"]
features = ["some", "awesome", "features"]
min_version = "0.80.0"

[author]
    name = "Tom치s Gonz치lez"
    homepage = "https:/tomasjgonzalez.com"

# If porting an existing theme
[original]
    author = "Tom치s Gonz치lez"
    homepage = "https:/tomasjgonzalez.com"
    repo = "Link to source code of original theme"